export const FIRSTVISIT = "FIRSTVISIT";
export const COINDATA = "COINDATA";
export const ADDCOIN = "ADDCOIN";
export const REMOVECOIN = "REMOVECOIN";
export const SETFAVORTIE = "SETFAVORTIE";
export const SETFILTEREDCOIN = "SETFILTEREDCOIN";
export const SETPRICES = "SETPRICES";
export const SETCURFAVORITE = "SETCURFAVORITE";
